name: calendar_event
description: "A new Flutter project."

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.5.2


dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8

  syncfusion_flutter_datepicker: 27.2.5
  freezed: ^2.5.7
  freezed_annotation: ^2.4.4
  json_annotation: ^4.9.0
  retrofit_generator: ^9.1.5
  retrofit: ^4.4.2
  dio: ^5.8.0+1
  flutter_bloc: ^9.1.0
  logger: ^2.5.0
  loader_overlay: ^4.0.3
  toastification: ^2.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0
  json_serializable: ^6.9.0
  build_runner: ^2.4.13




flutter:
  uses-material-design: true